# <font color = "red">[READ THIS] Before you start</font>
Welcome to UpLevel DIY projects! In this series, you're challenged to independently work (with our guidance) with data that you will collect to UpLevel yourself. 

We hope you're excited to embark on this adventure.
### Warning:
This isn't just any coding course or programmes, where you receive helper code as you move from one code block to another. 

This is when things get <em>real</em>.

In this project, you will receive instructions to execute a task along with an intended outcome. Most importantly, we will provide you with directions you can go to, to pick up code independently and implement it in this notebook.

Don't worry though, we'll be dropping lots of resources you can consult and these readings will contain everything you need to succeed. You can also perform independent research to find answers independently. You just have to read closely and pick out the parts that make most sense. 

<strong>We make you do this not because we're lazy bastards but because being able to indepedently find code is a highly underrated skill and that's something all companies look out for.</strong>

If you're really stuck and are on the verge of giving up, we gotchu fam. Head on over to https://www.facebook.com/UpLevelSG/ and post your questions there. 

### What we'll be doing:
In this project, we will do the following:

1. Acquire data on mental health of foreign students in Japan (Part I)
2. Perform exploratory data analysis and test a few hypotheses (Part II)
3. Transform the data for machine learning  (Part III)
4. Train a machine learning model based on several hypotheses (Part IV)

### Expectations:
We're not going to sugarcoat it - it'll be challenging at times. You have to promise to put in the time and effort to UpLevel yourself. 

But we promise you that it'll ultimately be fun and rewarding, and you'll come out of it stronger and more confident than before.

<div style="background-color: #78E8A3; padding: 20px">
<h3>Project Scenario</h3>
<p>You work in a university's health and wellness center.</p>
<p>Mental health is an area that is severely neglected, and can have very serious ramifications such as student self-harm and depression.</p> 
<p>You are determined to identify students at risk using data so you can help them as early as possible.</p>
<p>In this project, you will explore a dataset obtained from foreign students studying in a Japanese university.</p> 
</div>

### Step 1: Download the dataset and read the research publication
The dataset we are working with comes from the research of Nguyen et al (2019), where the authors obtained a record of 268 questionaire results of depression, acculturative stress, social connectedness, and help-seeking behaviour by a cohort of local and international students.

More details <a href = 'https://www.mdpi.com/2306-5729/4/3/124/htm'>here</a>.

Download the data <a href = 'https://www.mdpi.com/2306-5729/4/3/124/s1'>here</a> and unzip the file in your project folder.

We highly recommend reading Tables 1 and 2 in the publication to understand what the headers in your dataset mean, and we will refer to it from time to time.

### Step 2: Import pandas
Let's import pandas to read the data unzipped from the file you downloaded.

In [ ]:
# Step 2: Import pandas
import pandas as pd

### Step 3: Read CSV as DataFrame
Now that you've import the library, go ahead and read the CSV as a DataFrame

Make sure you have your variable alone in the last line of your code cell so you can preview your DataFrame.

In [23]:
# Step 3: Read CSVS as DataFrame
import pandas as pd
df = pd.read_csv('data.csv')
df.head(286)

,inter_dom,Region,Gender,Academic,Age,Age_cate,Stay,Stay_Cate,Japanese,Japanese_cate,...,Friends_bi,Parents_bi,Relative_bi,Professional_bi,Phone_bi,Doctor_bi,religion_bi,Alone_bi,Others_bi,Internet_bi
0,Inter,SEA,Male,Grad,24.0,4.0,5.0,Long,3.0,Average,...,Yes,Yes,No,No,No,No,No,No,No,No
1,Inter,SEA,Male,Grad,28.0,5.0,1.0,Short,4.0,High,...,Yes,Yes,No,No,No,No,No,No,No,No
2,Inter,SEA,Male,Grad,25.0,4.0,6.0,Long,4.0,High,...,No,No,No,No,No,No,No,No,No,No
3,Inter,EA,Female,Grad,29.0,5.0,1.0,Short,2.0,Low,...,Yes,Yes,Yes,Yes,No,No,No,No,No,No
4,Inter,EA,Female,Grad,28.0,5.0,1.0,Short,1.0,Low,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 4: Investigate what's wrong with the CSV
Wait a minute - if you displayed your DataFrame, you might have noticed something. The DataFrame you just read has a lot of missing data at the end. What's going on?

Take a better look at your DataFrame, more specifically the last few rows. There are two ways to do it:
1. Open your file in Excel and take a look
2. Use the .tail method of your DataFrame, and look at the last 20 rows

In [30]:
# Step 4: Use .tail to see what's up with the last 20 rows
import pandas as pd
df = pd.read_csv('data.csv')
df.tail(20)

,inter_dom,Region,Gender,Academic,Age,Age_cate,Stay,Stay_Cate,Japanese,Japanese_cate,...,Friends_bi,Parents_bi,Relative_bi,Professional_bi,Phone_bi,Doctor_bi,religion_bi,Alone_bi,Others_bi,Internet_bi
266,Dom,JAP,Male,Under,19.0,2.0,1.0,Short,5.0,High,...,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No
267,Dom,JAP,Male,Under,20.0,2.0,2.0,Medium,5.0,High,...,Yes,No,No,No,No,No,No,Yes,No,No
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,128,137,66,61,30,46,19,65,21,45
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,140,131,202,207,238,222,249,203,247,223
271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,128,137,66,61,30,46,19,65,21,45
273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,140,131,202,207,238,222,249,203,247,223
274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5: Remove the weird rows
When you check the data out - in Step 5 - you will see that there are random values at the bottom of the file that led to the many NaNs that you see at the bottom row.

Remove the last 18 rows, making sure that your resultant DataFrame has only <strong>268 rows x 50 columns</strong>.

There are many ways to do it, and here are some suggestions:
1. Slice the DataFrame (be careful about selecting the right index)
2. Drop NaN, using inter_dom as your subset reference column
3. Opening your CSV in Excel and deleting those values directly (make sure you redo Step 4 before going to Step 7)

In [32]:
# Step 5: Remove the last 18 rows
import pandas as pd 
df = pd.read_csv('data.csv')
df.drop([268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285], axis=0, inplace=True)
df.tail(20)

,inter_dom,Region,Gender,Academic,Age,Age_cate,Stay,Stay_Cate,Japanese,Japanese_cate,...,Friends_bi,Parents_bi,Relative_bi,Professional_bi,Phone_bi,Doctor_bi,religion_bi,Alone_bi,Others_bi,Internet_bi
248,Dom,JAP,Male,Under,21.0,3.0,3.0,Medium,5.0,High,...,Yes,Yes,Yes,No,No,No,No,No,No,No
249,Dom,JAP,Female,Under,19.0,2.0,1.0,Short,5.0,High,...,No,Yes,No,No,No,No,No,No,No,No
250,Dom,JAP,Male,Under,23.0,4.0,4.0,Long,5.0,High,...,Yes,No,No,No,No,No,Yes,No,No,Yes
251,Dom,JAP,Male,Under,23.0,4.0,5.0,Long,5.0,High,...,No,No,No,No,No,No,No,No,No,No
252,Dom,JAP,Female,Under,21.0,3.0,3.0,Medium,5.0,High,...,No,No,No,No,No,No,No,No,No,No
253,Dom,JAP,Female,Under,18.0,1.0,1.0,Short,5.0,High,...,Yes,Yes,No,Yes,No,No,No,No,No,No
254,Dom,JAP,Female,Under,21.0,3.0,3.0,Medium,5.0,High,...,No,No,No,No,No,No,No,No,No,No
255,Dom,JAP,Male,Under,22.0,3.0,4.0,Long,5.0,High,...,No,No,No,No,No,No,No,No,No,No
256,Dom,JAP,Female,Under,20.0,2.0,2.0,Medium,5.0,High,...,Yes,Yes,No,No,No,No,Yes,No,No,No
257,Dom,JAP,Male,Under,19.0,2.0,1.0,Short,5.0,High,...,No,No,No,No,Yes,No,No,Yes,No,Yes
258,Dom,JAP,Female,Under,18.0,1.0,1.0,Short,5.0,High,...,No,Yes,No,No,No,No,No,No,No,Yes
259,Dom,JAP,Male,Under,19.0,2.0,1.0,Short,3.0,Average,...,No,No,No,No,No,No,No,No,No,No
260,Dom,JAP,Female,Under,20.0,2.0,2.0,Medium,5.0,High,...,Yes,Yes,Yes,Yes,No,No,No,No,Yes,No
261,Dom,JAP,Female,Under,21.0,3.0,3.0,Medium,5.0,High,...,No,No,No,No,No,No,No,No,No,No
262,Dom,JAP,Male,Under,22.0,3.0,4.0,Long,5.0,High,...,Yes,Yes,Yes,No,No,No,No,No,No,No
263,Dom,JAP,Female,Under,21.0,3.0,4.0,Long,5.0,High,...,Yes,Yes,No,No,No,No,No,No,No,Yes
264,Dom,JAP,Female,Under,22.0,3.0,3.0,Medium,3.0,Average,...,Yes,Yes,Yes,No,No,No,No,No,No,No
265,Dom,JAP,Female,Under,19.0,2.0,1.0,Short,5.0,High,...,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No
266,Dom,JAP,Male,Under,19.0,2.0,1.0,Short,5.0,High,...,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No
267,Dom,JAP,Male,Under,20.0,2.0,2.0,Medium,5.0,High,...,Yes,No,No,No,No,No,No,Yes,No,No

### Step 6: Find the total number of missing values in each column
Now that we've a cleaner DataFrame, let's sum up the null values in each column. 

This is so that we can assess whether we need to clean the DataFrame some more.

<strong>Hint: Google "count missing values in each column pandas"</strong>

In [38]:
# Step 6: Count total of missing values in the DataFrame
import pandas as pd
df = pd.read_csv('data.csv')
df.isna()

,inter_dom,Region,Gender,Academic,Age,Age_cate,Stay,Stay_Cate,Japanese,Japanese_cate,...,Friends_bi,Parents_bi,Relative_bi,Professional_bi,Phone_bi,Doctor_bi,religion_bi,Alone_bi,Others_bi,Internet_bi
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
282,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
283,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
284,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
285,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True

### Step 7: Replace the missing values with median
Seems like only one column has missing values. It's not a lot, i.e. around 10% of the total number of rows, so you can just go ahead and replace the NaN with the median. 

Replace the missing values in 'Internet' column with the median of the column.

<strong>Hint: Google "replace nan with median pandas column"</strong>

In [73]:
# Step 7: Replace missing values in 'Internet' with median 
import pandas as pd
df = pd.read_csv('data.csv')
new_df = new_df.fillna(new_df.median())
new_df.info()
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 50 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   inter_dom        268 non-null    object
 1   Region           268 non-null    object
 2   Gender           268 non-null    object
 3   Academic         268 non-null    object
 4   Age              286 non-null    float64
 5   Age_cate         286 non-null    float64
 6   Stay             286 non-null    float64
 7   Stay_Cate        268 non-null    object
 8   Japanese         286 non-null    float64
 9   Japanese_cate    268 non-null    object
 10  English          286 non-null    float64
 11  English_cate     268 non-null    object
 12  Intimate         260 non-null    object
 13  Religion         268 non-null    object
 14  Suicide          268 non-null    object
 15  Dep              270 non-null    object
 16  DepType          271 non-null    object
 17  ToDep            286 non-null    float64
 18  DepSev           273 non-null    object
 19  ToSC             286 non-null    float64
 20  APD              286 non-null    float64
 21  AHome            286 non-null    float64
 22  APH              286 non-null    float64
 23  Afear            286 non-null    float64
 24  ACS              286 non-null    float64
 25  AGuilt           286 non-null    float64
 26  AMiscell         286 non-null    float64
 27  ToAS             286 non-null    float64
 28  Partner          286 non-null    float64
 29  Friends          286 non-null    float64
 30  Parents          286 non-null    float64
 31  Relative         286 non-null    float64
 32  Profess          286 non-null    float64
 33   Phone           286 non-null    float64
 34  Doctor           286 non-null    float64
 35  Reli             286 non-null    float64
 36  Alone            286 non-null    float64
 37  Others           286 non-null    float64
 38  Internet         286 non-null    float64
 39  Partner_bi       283 non-null    object
 40  Friends_bi       283 non-null    object
 41  Parents_bi       272 non-null    object
 42  Relative_bi      272 non-null    object
 43  Professional_bi  272 non-null    object
 44  Phone_bi         272 non-null    object
 45  Doctor_bi        272 non-null    object
 46  religion_bi      272 non-null    object
 47  Alone_bi         272 non-null    object
 48  Others_bi        272 non-null    object
 49  Internet_bi      272 non-null    object
dtypes: float64(26), object(24)
memory usage: 111.8+ KB
inter_dom          18
Region             18
Gender             18
Academic           18
Age                18
Age_cate           18
Stay               18
Stay_Cate          18
Japanese           18
Japanese_cate      18
English            18
English_cate       18
Intimate           26
Religion           18
Suicide            18
Dep                16
DepType            15
ToDep              18
DepSev             13
ToSC               18
APD                18
AHome              18
APH                18
Afear              18
ACS                18
AGuilt             18
AMiscell           18
ToAS               18
Partner            18
Friends            18
Parents            18
Relative           18
Profess            18
 Phone             18
Doctor             18
Reli               18
Alone              18
Others             18
Internet           44
Partner_bi          3
Friends_bi          3
Parents_bi         14
Relative_bi        14
Professional_bi    14
Phone_bi           14
Doctor_bi          14
religion_bi        14
Alone_bi           14
Others_bi          14
Internet_bi        14
dtype: int64

### Step 8: Check missing values again
Just repeat Step 7 to see if your replacement worked.

In [5]:
# Step 8: Check missing values in DataFrame
import pandas as pd
df = pd.read_csv('data.csv')
new_df = new_df.fillna(new_df.median())
new_df.info()

NameError: name 'new_df' is not defined

### Step 9: Export cleaned DataFrame as CSV
Now that you've done some cleaning up and filled in missing values, it's time to export the DataFrame as a CSV.

In [ ]:
# Step 9: Export DataFrame as CSV

### End of Part I
We've now come to the end of the first Part of the project. In this part you retrieve the data for this project, and then cleaned it up by removing unnecessary rows of data and filled in missing data. 

In the next Part, we will perform some exploratory data analysis and test several hypotheses.